services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: tontine_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: 
      context: ./server
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgresql://postgres:password123@postgres:5432/tontine_db
      NODE_ENV: development
      PORT: 3003
    ports:
      - "3003:3003"
    depends_on:
      - postgres

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      VITE_API_URL: http://backend:3001/api
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data:
