name: Deploy to Render

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install Dependencies
        run: |
          npm ci
          cd server && npm ci
          cd ..
          
      - name: Build
        run: |
          npm run build
          cd server && npm run build
          
      - name: Deploy to Render
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
        run: |
          curl -X POST "https://api.render.com/v1/services/$RENDER_SERVICE_ID/deploys" \
            -H "Authorization: Bearer $RENDER_API_KEY"
            
      # Pour Fly.io
      - name: Deploy to Fly.io
        run: |
          curl -L https://fly.io/install.sh | sh
          fly auth token ${{ secrets.FLY_API_TOKEN }}
          fly deploy
